### ISSUE TITLE
可以尝试用 GitBook 发布

### ISSUE THREAD

**Issue by yzyzsun** [zhuojiteam/Tutorial-for-newbie#3]
https://github.com/GitbookIO/gitbook

**Comment by lulucici** [comment]
有道理，不过窝本来也想重新整理过再发Gitbook...现在这个版本感觉读起来不是很友好QAQ

**Comment by Axure** [comment]
后续发展？@lulucici

**Comment by Axure** [comment]
Done.
Published [here](https://www.gitbook.com/book/axure/tutorial-for-newbie/details).
